language: java
jdk:
- oraclejdk8
install: true
addons:
  sonarcloud:
    organization: xm-online
    token:
      secure: kG3J39LbGrIvnflOBGh+xEiWbGro23kBUoOB8NUhpkp1P5S18pn9U5Knt7Ch9eBH1jDLxkfDYB6j2f/tc3DWgGfdaWCsCYAgR2CBKz8X8NMBM3laJqG7hM0IeKsbxwlBz9qR2h4bbhCOwDSJAWpY+UBhCbnakQlh+DnG4LN83K58Go0J/dME02Zskc5EdqjQUxGAUF9K1AfsHJOH9cVCJX4q20o7xPCQKxzJ7dHKUt2OxsscKwcm6KL0tgU3BFfl6vE8uQP6J6mvw768kBb+uQTlH50UaHt95S74saHr6zLJUCXWbvWmOrBmMZWsIqJW8N8uJrPfsJhwDHHKgAQ8kebzVilJjQlostqZuiWpgrP0KZWXtn3UUllC0xMlbZtIIlyyEvQu+hObe7UjlluJFZcRT64KXZf1yl/9mvRo7P2A6lR1G31f00iyfhaQIPNJR5iJ6md8zqg4qkhZKq9hLykvFfEHn5PwSGUUUvpDpQ75GEvknY053XOACYzjK6vteDAOpbvzkvABoW03EcBjWrY9WY11FkbwHUZ3UWnQKqIvge0d462evCPKmGe1u3EF7x0fk+gGEB+Q8HvUCg/DI3YjnmnCNWaTi5TOMSjyz3POJdJNrF0baBW2oAcyfyIiULV0PaW0zE041GnpM+28pZS5PXNbL6hLMeVuC67uZSs=
    branches:
    - master
script:
- set -e
- ./gradlew --no-daemon --refresh-dependencies clean check test
- ./gradlew -x test -Pprod --no-daemon bootRepackage
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export DOCKER_REPO=$(echo  -n $TRAVIS_REPO_SLUG | sed -e 's/^xm-online\//xmonline\//g'); 
- docker build -t $DOCKER_REPO:$TRAVIS_BRANCH -t $DOCKER_REPO:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER  
  --label commit_id="$TRAVIS_COMMIT" --label commit_message="$TRAVIS_COMMIT_MESSAGE" 
  -f src/main/docker/Dockerfile .
- docker push $DOCKER_REPO:$TRAVIS_BRANCH
- docker push $DOCKER_REPO:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER
- if [ "$TRAVIS_BRANCH" == "master" ]; then 
  docker tag $DOCKER_REPO:$TRAVIS_BRANCH $DOCKER_REPO:latest; 
  docker push $DOCKER_REPO:latest; 
  export SONAR_PK=$(echo  -n $TRAVIS_REPO_SLUG | sed -e 's/\//:/g'); 
  ./gradlew -x test --no-daemon sonarqube -Dsonar.projectKey="$SONAR_PK" -Dsonar.projectName="$SONAR_PK" -Dsonar.java.binaries="." -Dsonar.projectVersion="$TRAVIS_BRANCH"; fi
cache:
  directories:
  - "~/.gradle/"
env:
  global:
  - secure: VvzxJhB48sTSWAD4zfhGHu0jw5Jk6/1BOEaElZ10b5IX5M4daP8fFHrueANMVhpue63mhhcmojR4rC/mFJLOmo4cP7JwsB0H0IUyUPd/eye3RTX/bQ1b7vgyQF0FI1fB9+pq+Co24nK5j49R/JjW4kZvjZh/b8A8VX08WUANQNyEJ5qaB6NVn2K+CgQQH3GlEtkYfn/5eG5UDcuyaz/wLeift6/hPuiMyvSWW+55MlwwNFkq1VtHEAcvNbmFVbb+fGoye+TqCKC3K5vz24PBmU6P8+uY+IhdqfYGaK5TNL0y90AcafrO/AHX4OtvM2L0DQCtx3N8FvfmQB3x8C+o/Vc+swWO5SSQ5F7Vq3H1XAb8ZNo7+jTZ37kIXqN/U9Ffn9P6mrk10rOfATS4AqzNOLV2NCtOMokoqQIYm2G9O6mGiRlKuOvMrR8C9NdqGFIih4jhW1jdyJqCHXoP8jSs7ZZdPo2Mjw+IsemO5cvw7fWDQYGskT8RKRecAxUNzbe8vsIFT3KHzb8Pn40a/4cGE8dH0/Qz/kWxl5rfvsWm6XmdLoqpYhW+clHXuYKe/r14ZAtW8IUM3Q4ynf5pT6TU1TB3CBbJM4f1+X+/r6rZiw7NPEjcvHkRYtWoYy83PGlapKVRbvPIZ7dMVzPvfhkEp4N8dshTuj2AQPfvCLyGMys=
  - secure: Dg1DdFIzseRDLRdB4pxxOCpDFg1YehNd3WbHNy/PlybGf60Ri5yfyPBpHqSeR/usggwY7QSbBiHtqiHCS/3cBGsT+NyGDseRHOUaClHhAOOPPxKionWHmtKQz9DHGiPDYXpSb1uWLCEWZk7XVw8UAI7GproIUVL2tcn5GfY1aY/F75FpG9io9FG4jbPHAA6D2XiWR4NgJheIcVBwklpK/UjDn6dnUMvISFG2vu/3ouC1roTA5hfm4zkM050+JmZusU3P6pFYYm8fAXKzvjkKRDXzh0w/45HkSsleuzUXSrNee1Dj1Mj23xQ/LMufIVBd7zg+6LPPE2F3RvInr2c/le3l8XsFlODcPCm6tGb/knWe7F9lH1Al7NXX3DyXPmkm1QCl0NA9BpiKD7zmdAN93VsniPAlGPhIIppqldlCLw3uQgcORyRjPAMDkebatHO2STgVXklNSQrkTEwu/3CKqxL0kNgqJxMTNtSiS6S0aqwB3+wuhbZ8OfwouiWY0pQiUtabH9X4QxnZO7AbVXnEdfaUJV1OrLE5SOXczOkpoZuiQ52bKeIbglzsHNLEDdZNDe5MMeSeXxi14PzOU3AyHS0QkwFu3MFTHnd5PAOcPCEfp/kTZTVxTiqaxCJVgk1JojGyjWNyqgjZRymk9KuihJxKZc4+GK+Dh8kXmseKcpM=
